### ISSUE TITLE
Tasks for Milestone 3

### ISSUE THREAD

**Issue by thuanGIT** [data301-2020-winter2/course-project-group_1039#50]
Hey everyone,

Haneen just commented on our work so we need to work on it as soon as possible. Here are our tasks for this sprint:

@RitaLam 
- [x] Edit individual EDA to exclude Task 5
- [x] Move collective work to Tableu after data is processed.

@lhenon999 
- [ ] Edit individual EDA to exclude Task 5.
- [ ] Check processed data

@thuanGIT 
- [x] Process data and save to process folder
- [x] Edit individual EDA to exclude Task 5

There are not a lot of work for this milestone so we might have more time. But please **keep track on the deadlines**!

**Comment by thuanGIT** [comment]
Well done everyone!
