### ISSUE TITLE
Tasks for Milestone 4 

### ISSUE THREAD

**Issue by thuanGIT** [data301-2020-winter2/course-project-group_1039#60]
Hey @RitaLam @lhenon999,

We are approaching the final run of this project. Here are some tasks that we need to do.

@RitaLam 
- [x] Attend the final meeting.
- [x] Work on your own Dashboard (Lab 7)
- [x] Present your work to the group for voting.
- [x] Collaborate on the presentation video for the final dashboard.
- [x] Check all documentations (all README.md files)
- [x] Submit final dashboard on Tableu server.

@lhenon999 

- [ ] ~~Attend the final meeting~~ **(Missed)**.
- [x] Edit individual EDA to exclude Task 5.
- [x] Work on your own Dashboard (Lab 7)
- [x] Present your work to the group for voting.
- [x] Collaborate on the presentation video for the final dashboard.
- [x] Check all documentations (all README.md files)

@thuanGIT 
- [x] Attend the final meeting.
- [x] Work on your own Dashboard (Lab 7)
- [x] Present your work to the group for voting.
- [x] Collaborate on the presentation video for the final dashboard.
- [x] Check all documentations (all README.md files)
- [x] Post the final presentation video to Somewhere.

**Note: Any unfinished tasks in the previous sprint will be carried forward.**

**Comment by RitaLam** [comment]
Thank you so much for keeping us on track Jamie!

I think we shall have at least two meetings before the final submission:
1.  making the dashboard and divide the work (cant make Jamie do everything again)
2. Video making to present out dashboard)
Let me know what your guys think. I know it's Easter but let's all spare half an hour meet briefly this weekend, and another time next weekend before the final deadline. I can create a pull later for the meeting time so we can decide the time to meet.
I know we all have finals coming up so let's just get this one done!
Rita

**Comment by RitaLam** [comment]
Milestone #4 meeting time this week 

[![](https://api.gh-polls.com/poll/01F28ADFZ56TWJEW54Z7MSCYXZ/Saturday)](https://api.gh-polls.com/poll/01F28ADFZ56TWJEW54Z7MSCYXZ/Saturday/vote)
[![](https://api.gh-polls.com/poll/01F28ADFZ56TWJEW54Z7MSCYXZ/Sunday)](https://api.gh-polls.com/poll/01F28ADFZ56TWJEW54Z7MSCYXZ/Sunday/vote)
[![](https://api.gh-polls.com/poll/01F28ADFZ56TWJEW54Z7MSCYXZ/Monday)](https://api.gh-polls.com/poll/01F28ADFZ56TWJEW54Z7MSCYXZ/Monday/vote)

**Comment by RitaLam** [comment]
Remember guys Today at 7 pm is our meeting! Use the zoom link in the other issue. See you guys soon :)

**Comment by thuanGIT** [comment]
Well done everyone!
